version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # .env "MYSQL_ROOT_PASSWORD: my-secret-pw"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL 8.0의 기본 인증 플러그인 설정
    restart: always

volumes:
  mysql_data:
    name: mysql_data
