# 베이스 이미지 선택
FROM python:3.9.18-alpine

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

#  실행
CMD ["uvicorn", "app.main:app", "--reload"]